spring:
  datasource:
    url: jdbc:sqlserver://projecthariom.database.windows.net:1433;database=projectDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: hariom@hariom@projecthariom
    password: hariom@satvik1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9898
#
#logging:
#  level:
#    org.springframework: DEBUG


